name: Monthly Release
uses: imjohnbo/issue-bot@v2.3.1
with:
  repo-token: ${{ secrets.GITHUB_TOKEN }}
on:
  schedule:
   - cron: 0 0 1 * *  # Every 1st day of the month at 0000 – https://crontab.guru

jobs:
  daily_standup:
    name: Daily Standup
    runs-on: ubuntu-latest
    steps:

    # Repo code checkout required if `template` is used
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: issue-bot
      uses: imjohnbo/issue-bot@v2
      with:
        assignees: "Dr. Toboggan" # GitHub handles without the @
        labels: "Type: Release Thread"
        pinned: true
        close-previous: true
        template: ".github/ISSUE_TEMPLATE/RELEASE_TEMPLATE.md
